Bump sigstore, remove deprecated email identity setting (#37)
* treewide: bump to sigstore 0.8.3, remove deprecated setting

Signed-off-by: William Woodruff <william@trailofbits.com>

* workflows/selftest: remove old selftest

Signed-off-by: William Woodruff <william@trailofbits.com>

* README: fix accidental edit

Signed-off-by: William Woodruff <william@trailofbits.com>

* action: toggle verification

Signed-off-by: William Woodruff <william@trailofbits.com>

* action: lintage

Signed-off-by: William Woodruff <william@trailofbits.com>

* workflows/selftest: exercise verification

Signed-off-by: William Woodruff <william@trailofbits.com>

* action: prevent users from specifying ineffective verification options

Signed-off-by: William Woodruff <william@trailofbits.com>

* workflows/selftest: experiment with xfails

Signed-off-by: William Woodruff <william@trailofbits.com>

* workflows/selftest: more experimenting

Signed-off-by: William Woodruff <william@trailofbits.com>

* selftest: fix xfail

Signed-off-by: William Woodruff <william@trailofbits.com>

* workflows/selftest: xfail matrix

Signed-off-by: William Woodruff <william@trailofbits.com>

Signed-off-by: William Woodruff <william@trailofbits.com>

diff --git a/.github/workflows/selftest.yml b/.github/workflows/selftest.yml
--- a/.github/workflows/selftest.yml
+++ b/.github/workflows/selftest.yml
@@ -73,7 +73,7 @@ jobs:
           certificate: ./test/custom_certificate.crt
           staging: true
 
-  selftest-verify-cert-identity:
+  selftest-verify:
     runs-on: ubuntu-latest
     if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
     steps:
@@ -83,35 +83,54 @@ jobs:
         id: sigstore-python
         with:
           inputs: ./test/artifact.txt
+          verify: true
           verify-cert-identity: https://github.com/sigstore/gh-action-sigstore-python/.github/workflows/selftest.yml@${{ github.ref }}
-          staging: true
-
-  # NOTE(ww): Remove once `verify-cert-email` is removed.
-  selftest-verify-cert-email:
-    runs-on: ubuntu-latest
-    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
-    steps:
-      - uses: actions/checkout@v3
-      - name: Sign artifact and publish signature
-        uses: ./
-        id: sigstore-python
-        with:
-          inputs: ./test/artifact.txt
-          verify-cert-email: https://github.com/sigstore/gh-action-sigstore-python/.github/workflows/selftest.yml@${{ github.ref }}
-          staging: true
-
-  selftest-verify-issuer:
-    runs-on: ubuntu-latest
-    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
-    steps:
-      - uses: actions/checkout@v3
-      - name: Sign artifact and publish signature
-        uses: ./
-        id: sigstore-python
-        with:
-          inputs: ./test/artifact.txt
           verify-oidc-issuer: https://token.actions.githubusercontent.com
           staging: true
+
+  selftest-xfail-verify-missing-options:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        config:
+          # fails if both verify-cert-identity and verify-oidc-issuer are missing
+          - verify: true
+
+          # fails if either is missing
+          - verify: true
+            verify-oidc-issuer: https://token.actions.githubusercontent.com
+
+          - verify: true
+            verify-cert-identity: https://github.com/sigstore/gh-action-sigstore-python/.github/workflows/selftest.yml@${{ github.ref }}
+
+          # fails if either option is passed while verification is disabled
+          - verify: false
+            verify-oidc-issuer: https://token.actions.githubusercontent.com
+
+          - verify: false
+            verify-cert-identity: https://github.com/sigstore/gh-action-sigstore-python/.github/workflows/selftest.yml@${{ github.ref }}
+
+    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
+    steps:
+      - uses: actions/checkout@v3
+      - name: Sign artifact and publish signature
+        continue-on-error: true
+        uses: ./
+        id: sigstore-python
+        with:
+          inputs: ./test/artifact.txt
+          verify: ${{ matrix.config.verify }}
+          verify-oidc-issuer: ${{ matrix.config.verify-oidc-issuer }}
+          verify-cert-identity: ${{ matrix.config.verify-cert-identity }}
+          staging: true
+      - name: Check failure
+        env:
+          XFAIL: ${{ steps.sigstore-python.outcome == 'failure' }}
+          JOB_NAME: ${{ github.job }}
+        run: |
+          echo "xfail ${JOB_NAME}: ${XFAIL}"
+
+          [[ "${XFAIL}" == "true" ]] || { >&2 echo "expected step to fail"; exit 1; }
 
   selftest-identity-token:
     runs-on: ubuntu-latest
