selftest: fix xfail
Signed-off-by: William Woodruff <william@trailofbits.com>

diff --git a/.github/workflows/selftest.yml b/.github/workflows/selftest.yml
--- a/.github/workflows/selftest.yml
+++ b/.github/workflows/selftest.yml
@@ -104,10 +104,11 @@ jobs:
       - name: Check failure
         env:
           XFAIL: ${{ steps.sigstore-python.outcome == 'failure' }}
+          JOB_NAME: ${{ github.job }}
         run: |
-          xfail: "${XFAIL}"
+          echo "xfail ${JOB_NAME}: ${XFAIL}"
 
-          [[ "${XFAIL}" == "true" ]] || exit 1
+          [[ "${XFAIL}" == "true" ]] || { >&2 echo "expected step to fail"; exit 1; }
 
   selftest-identity-token:
     runs-on: ubuntu-latest
