workflows/selftest: add more xfail selftests
Signed-off-by: William Woodruff <william@trailofbits.com>

diff --git a/.github/workflows/selftest.yml b/.github/workflows/selftest.yml
--- a/.github/workflows/selftest.yml
+++ b/.github/workflows/selftest.yml
@@ -22,6 +22,33 @@ jobs:
         with:
           inputs: ./test/artifact.txt
 
+  selftest-xfail-invalid-inputs:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        input:
+          # We forbid inputs that look like flags
+          - "--this-should-not-work"
+          # We fail if the input doesn't exist
+          - "/tmp/extremely-nonexistent-file"
+    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
+    steps:
+      - uses: actions/checkout@v3
+      - name: Sign artifact and publish signature
+        continue-on-error: true
+        uses: ./
+        id: sigstore-python
+        with:
+          inputs: ${{ matrix.input }}
+      - name: Check failure
+        env:
+          XFAIL: ${{ steps.sigstore-python.outcome == 'failure' }}
+          JOB_NAME: ${{ github.job }}
+        run: |
+          echo "xfail ${JOB_NAME}: ${XFAIL}"
+
+          [[ "${XFAIL}" == "true" ]] || { >&2 echo "expected step to fail"; exit 1; }
+
   selftest-staging:
     runs-on: ubuntu-latest
     if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
